1 preprocessing  and cleaning
train test split
bow tfidf word2vec
train ml algo

In [1]:
#load
import pandas as pd
data=pd.read_csv("all_kindle_review .csv")

In [2]:
data.head()

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0             0       11539  B0033UV8HI  [8, 10]       3   
1             1        5957  B002HJV4DE   [1, 1]       5   
2             2        9146  B002ZG96I4   [0, 0]       3   
3             3        7038  B002QHWOEU   [1, 3]       3   
4             4        1776  B001A06VJ8   [0, 1]       4   

                                          reviewText   reviewTime  \
0  Jace Rankin may be short, but he's nothing to ...   09 2, 2010   
1  Great short read.  I didn't want to put it dow...   10 8, 2013   
2  I'll start by saying this is the first of four...  04 11, 2014   
3  Aggie is Angela Lansbury who carries pocketboo...   07 5, 2014   
4  I did not expect this type of book to be in li...  12 31, 2012   

       reviewerID  reviewerName                   summary  unixReviewTime  
0  A3HHXRELK8BHQG        Ridley  Entertaining But Average      1283385600  
1  A2RGNZ0TRF578I  Holly Butler   Terrific menage scenes!      1381190400  
2  A3S0H2HV6U1I7F       Merissa          Snapdragon Alley      1397174400  
3   AC4OQW3GZ919J    Cleargrace    very light murder cozy      1404518400  
4  A3C9V987IQHOQD      Rjostler                      Book      1356912000

In [3]:
data.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'asin', 'helpful', 'rating', 'reviewText',
       'reviewTime', 'reviewerID', 'reviewerName', 'summary',
       'unixReviewTime'],
      dtype='object')

In [4]:
data=data[["reviewText","rating"]]
data.head()

reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [5]:
data.shape

(12000, 2)

In [6]:
# missing
data.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [7]:
data["rating"].unique()

array([3, 5, 4, 2, 1], dtype=int64)

In [8]:
data["rating"].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [9]:
# preprocessing and cleaning
# 1) review : positive(1) negative(0) for sentiment analysis
data["rating"]=data["rating"].apply(lambda x: 0 if x<3 else 1)

In [10]:
data.head()

reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       1
1  Great short read.  I didn't want to put it dow...       1
2  I'll start by saying this is the first of four...       1
3  Aggie is Angela Lansbury who carries pocketboo...       1
4  I did not expect this type of book to be in li...       1

In [11]:
data["rating"].unique()
data["rating"].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [12]:
# 2) lowering all cases
data["reviewText"]=data["reviewText"].str.lower()
data["reviewText"]

0        jace rankin may be short, but he's nothing to ...
1        great short read.  i didn't want to put it dow...
2        i'll start by saying this is the first of four...
3        aggie is angela lansbury who carries pocketboo...
4        i did not expect this type of book to be in li...
                               ...                        
11995    valentine cupid is a vampire- jena and ian ano...
11996    i have read all seven books in this series. ap...
11997    this book really just wasn't my cuppa.  the si...
11998    tried to use it to charge my kindle, it didn't...
11999    taking instruction is a look into the often hi...
Name: reviewText, Length: 12000, dtype: object

In [13]:
print(data["reviewText"].dtype)
print(type(data["reviewText"]))

"""type(review_column) → What container is this? → pandas.Series

review_column.dtype → What kind of data is inside? → object (text), int64, float64, etc."""

""""text" → str

123 → int

45.6 → float

True → bool

Pandas sees different types, so it treats them all as Python objects → thus the dtype is object"""


object
<class 'pandas.core.series.Series'>


'"text" → str\n\n123 → int\n\n45.6 → float\n\nTrue → bool\n\nPandas sees different types, so it treats them all as Python objects → thus the dtype is object'

In [14]:
# !pip install beautifulsoup4


In [15]:
data.head()

reviewText  rating
0  jace rankin may be short, but he's nothing to ...       1
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

In [16]:
# !pip install nltk

In [17]:
# !pip install lxml


In [18]:
# 3) remove special characters
                                       
import re
import nltk
from nltk.corpus import stopwords
from bs4 import BeautifulSoup

nltk.download('stopwords')

df = data.copy()

# Cache stopwords once (important!)
stop_words = set(stopwords.words("english"))

# 1) Remove special characters (preserve spaces)
data["reviewText"] = data["reviewText"].apply(lambda x: re.sub(r'[^a-zA-Z0-9 ]+', '', str(x)))

# 2) Remove stopwords
data["reviewText"] = data["reviewText"].apply(
    lambda x: " ".join([word for word in x.split() if word.lower() not in stop_words])
)

# 3) Remove URLs
data['reviewText'] = data['reviewText'].apply(
    lambda x: re.sub(r'(http|https|ftp|ssh)://\S+', '', str(x))
)

# 4) Remove HTML tags
# data['reviewText'] = data['reviewText'].apply(
#     lambda x: BeautifulSoup(x, 'lxml').get_text()
# )

# 5) Remove extra spaces
data['reviewText'] = data['reviewText'].apply(lambda x: " ".join(x.split()))


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [19]:
from bs4 import BeautifulSoup

html = "<p>Hello <b>Umer</b></p>"
soup = BeautifulSoup(html, "html.parser")
print(soup.text)  # Output: Hello Umer


Hello Umer


In [20]:

data.head()

reviewText  rating
0  jace rankin may short hes nothing mess man hau...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four books wasnt expect...       1
3  aggie angela lansbury carries pocketbooks inst...       1
4  expect type book library pleased find price right       1

In [21]:

## Lemmatizer
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

df['reviewText']=df['reviewText'].apply(lambda x:lemmatize_words(x))

In [22]:
df.head()

reviewText  rating
0  jace rankin may be short, but he's nothing to ...       1
1  great short read. i didn't want to put it down...       1
2  i'll start by saying this is the first of four...       1
3  aggie is angela lansbury who carry pocketbook ...       1
4  i did not expect this type of book to be in li...       1

In [23]:

## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df['reviewText'],df['rating'],
                                              test_size=0.20)

In [24]:
# vectorziation
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer()
X_train_bow=bow.fit_transform(X_train).toarray()
X_test_bow=bow.transform(X_test).toarray()

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
X_train_tfidf=tfidf.fit_transform(X_train).toarray()
X_test_tfidf=tfidf.transform(X_test).toarray()

X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [25]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow=GaussianNB().fit(X_train_bow,y_train)
nb_model_tfidf=GaussianNB().fit(X_train_tfidf,y_train)

In [26]:

from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

y_pred_bow=nb_model_bow.predict(X_test_bow)

y_pred_tfidf=nb_model_bow.predict(X_test_tfidf)
print(confusion_matrix(y_test,y_pred_bow))

[[548 264]
 [747 841]]


In [ ]:

print("BOW accuracy: ",accuracy_score(y_test,y_pred_bow))

BOW accuracy:  0.57875


In [28]:

confusion_matrix(y_test,y_pred_tfidf)

array([[542, 270],
       [741, 847]], dtype=int64)

In [29]:
print("TFIDF accuracy: ",accuracy_score(y_test,y_pred_tfidf))

TFIDF accuracy:  0.57875


In [30]:
X_train_bow[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [31]:
corpus=[]
for sent in df["reviewText"]:
    corpus.append(sent)
corpus


['jace rankin may be short, but he\'s nothing to mess with, a the man who wa just hauled out of the saloon by the undertaker know now. he\'s a famous bounty hunter in oregon in the 1890s who, when he shot the man in the saloon, just finished a year long quest to avenge his sister\'s murder and is now trying to figure out what to do next. when the snotty-nosed farm boy he just rescued from a gang of bully offer him money to kill a man who forced him off his ranch, he reluctantly agrees to bring the man to justice, but not to kill him outright. but, first he need to tell his sister\'s widower the news.kyla "kyle" springer bailey ha been riding the trail and sleeping on the ground for the past month while trying to find jace. she want revenge on the man who killed her husband and took her ranch, amongst other crimes, and she\'s not so keen on the detour jace want to take. but she realizes she\'s out of options, so she hide behind her boy persona a best she can and try to keep pace. when a

In [32]:
from nltk import sent_tokenize, word_tokenize
words=[]
for sentt in corpus:
    sent_token=word_tokenize(sentt)
    words.append(sent_token)

In [33]:
words

[['jace',
  'rankin',
  'may',
  'be',
  'short',
  ',',
  'but',
  'he',
  "'s",
  'nothing',
  'to',
  'mess',
  'with',
  ',',
  'a',
  'the',
  'man',
  'who',
  'wa',
  'just',
  'hauled',
  'out',
  'of',
  'the',
  'saloon',
  'by',
  'the',
  'undertaker',
  'know',
  'now',
  '.',
  'he',
  "'s",
  'a',
  'famous',
  'bounty',
  'hunter',
  'in',
  'oregon',
  'in',
  'the',
  '1890s',
  'who',
  ',',
  'when',
  'he',
  'shot',
  'the',
  'man',
  'in',
  'the',
  'saloon',
  ',',
  'just',
  'finished',
  'a',
  'year',
  'long',
  'quest',
  'to',
  'avenge',
  'his',
  'sister',
  "'s",
  'murder',
  'and',
  'is',
  'now',
  'trying',
  'to',
  'figure',
  'out',
  'what',
  'to',
  'do',
  'next',
  '.',
  'when',
  'the',
  'snotty-nosed',
  'farm',
  'boy',
  'he',
  'just',
  'rescued',
  'from',
  'a',
  'gang',
  'of',
  'bully',
  'offer',
  'him',
  'money',
  'to',
  'kill',
  'a',
  'man',
  'who',
  'forced',
  'him',
  'off',
  'his',
  'ranch',
  ',',
  'he',

In [34]:
# !pip install gensim
# !pip uninstall numpy gensim -y
# !pip install numpy --upgrade
# !pip install gensim --upgrade


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer()
X_train_bow=bow.fit_transform(X_train).toarray()
X_test_bow=bow.transform(X_test).toarray()

In [43]:
# avg word2vec
import gensim
model = gensim.models.Word2Vec(X_train, vector_size=100, window=5, min_count=1, workers=4)


In [45]:

import numpy as np

def avg_word2vec(sentence, model, vector_size):
    valid_words = [word for word in sentence if word in model.wv]
    if not valid_words:
        return np.zeros(vector_size)  # If no words found in vocab
    return np.mean([model.wv[word] for word in valid_words], axis=0)


In [46]:

X_train_vecs = np.array([avg_word2vec(s, model, model.vector_size) for s in X_train])
X_test_vecs = np.array([avg_word2vec(s, model, model.vector_size) for s in X_test])


array([[-0.02975363,  0.16932003,  0.11445587, ..., -0.07427064,
         0.13314436,  0.11607914],
       [-0.07865172,  0.12721428,  0.04853716, ..., -0.09420624,
         0.05114532,  0.11312759],
       [-0.05479282,  0.13996735,  0.09392884, ..., -0.05595695,
         0.12895615,  0.16528505],
       ...,
       [-0.06815302,  0.14357916,  0.09509594, ..., -0.05871934,
         0.08696348,  0.12710902],
       [-0.06750534,  0.1442814 ,  0.10693358, ..., -0.04960771,
         0.10163389,  0.13995267],
       [-0.05722728,  0.1382487 ,  0.097541  , ..., -0.07607421,
         0.09677133,  0.12454554]], dtype=float32)

In [50]:
X_train_vecs.shape

(9600, 100)

In [51]:
X_test_vecs.shape

(2400, 100)

In [49]:
import pandas as pd

df_vectors = pd.DataFrame(X_train_vecs)
df_vectors.head()


0         1         2         3         4         5         6   \
0 -0.062633  0.117417  0.075324 -0.044571 -0.058295 -0.013443  0.014579   
1 -0.087279  0.165523  0.085256 -0.024772 -0.037566  0.004086 -0.022836   
2 -0.047607  0.135398  0.120687 -0.043266 -0.091817 -0.012487 -0.011716   
3 -0.044778  0.128950  0.114085 -0.030565 -0.075353 -0.009002  0.021646   
4 -0.045963  0.145141  0.111031 -0.047524 -0.100763 -0.013624  0.023719   

         7         8         9   ...        90        91        92        93  \
0  0.051989 -0.066956 -0.197502  ...  0.142223 -0.019911 -0.004640 -0.055499   
1  0.020153 -0.028117 -0.186808  ...  0.145331 -0.000907 -0.014088 -0.080895   
2  0.054245 -0.056984 -0.217194  ...  0.162219 -0.039582 -0.014037 -0.076411   
3  0.054082 -0.069249 -0.217749  ...  0.153978 -0.049647 -0.017289 -0.030146   
4  0.063288 -0.034589 -0.237870  ...  0.130624 -0.053388  0.001316 -0.067408   

         94        95        96        97        98        99  
0  0.017457 -0.297095  0.178868 -0.058052  0.104314  0.126081  
1  0.014968 -0.306275  0.192409 -0.088292  0.120165  0.133445  
2  0.034873 -0.312712  0.190016 -0.046122  0.114138  0.123427  
3  0.023162 -0.299519  0.170331 -0.016419  0.108210  0.094420  
4  0.032469 -0.292849  0.205595 -0.048897  0.094673  0.086119  

[5 rows x 100 columns]

In [52]:
from sklearn.naive_bayes import GaussianNB
nb_model_w2v=GaussianNB().fit(X_train_vecs,y_train)
y_pred_w2v=nb_model_w2v.predict(X_test_vecs)

print("BOW accuracy: ",accuracy_score(y_test,y_pred_w2v))

BOW accuracy:  0.6254166666666666
